### ISSUE TITLE
'Document' object has no attribute 'getToC'

### ISSUE THREAD

**Issue by Wizarzz** [Enoch2090/Nyquisis#5]
python版本：3.12
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\nyquisis.exe\__main__.py", line 7, in <module>
  File "C:\Python312\Lib\site-packages\nyquisis\nyquisis.py", line 173, in main
    drop_duplicates(fpath, output=output)
  File "C:\Python312\Lib\site-packages\nyquisis\nyquisis.py", line 120, in drop_duplicates
    toc = file.getToC()
          ^^^^^^^^^^^
AttributeError: 'Document' object has no attribute 'getToC'. Did you mean: 'get_oc'?

**Comment by Enoch2090** [comment]
Probably due to fitz(PyMuPDF)'s API changes. Will try to fix dependencies when I'm avaliable
